version: 2
jobs:
    prepare:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - restore_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
            - run: 
                name: install-npm
                command: npm install
            - save_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "node_modules"
    test:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - restore_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
            - run: 
                name: test
                command: npm run test-headless
            - store_artifacts:
                path: coverage
                prefix: coverage
    lint:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - restore_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
            - run: 
                name: lint
                command: npm run lint
    android:
        docker:
            - image: circleci/android:api-26-aplha
        steps:
            - checkout
            - restore_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
            - run: 
                name: cordova
                command: sudo npm install -g ionic cordova
            - run:
                name: prepare
                command: npm run prepare-android
            - save_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
            - run:
                name: build
                command: npm run release-android
            - store_artifacts:
                path: apk
                prefix: android
workflows:
  version: 2
  build_and_test:
    jobs:
        - prepare
        #- test:
        #    requires:
        #        - prepare
        #- lint:
        #    requires:
        #        - prepare
        - android:
            requires: 
                - prepare
      
