version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - restore_cache:
                key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
            - run: 
                name: install-angular-cli
                command: npm install @angular/cli
            - run: 
                name: install-npm
                command: npm install
            - save_cache:
                key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "./node_modules"
    test:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run: 
                name: test
                command: node_modules/@angular/cli/bin/ng test --watch=false --codeCoverage=true --browsers=ChromeHeadlessCI
            - store_artifacts:
                path: coverage
                prefix: coverage
    lint:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - run: 
                name: lint
                command: node_modules/@angular/cli/bin/ng lint
workflows:
  version: 2
  build_and_test:
    jobs:
        - build
        - test:
            requires:
                - build
        - lint:
            requires:
                - build
      