version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - restore_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
            - run: 
                name: install-npm
                command: npm install
            - save_cache:
                key: AngularCircleCI-v1.0-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "node_modules"
    test:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run: 
                name: test
                command: npm run test-headless
            - store_artifacts:
                path: coverage
                prefix: coverage
    lint:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - run: 
                name: lint
                command: npm run lint
workflows:
  version: 2
  build_and_test:
    jobs:
        - build
        - test:
            requires:
                - build
        - lint:
            requires:
                - build
      
